---
# tasks file for roles/postgresql
- name: deploy postgresql runtime
  block:
    - name: create dir
      ansible.builtin.file:
        path: "{{ apps.postgresql.app_base_dir }}"
        owner: "{{ servers[group_names[0]]['sys_users'][0].user.name }}"
        group: "{{ servers[group_names[0]]['sys_users'][0].user.groups }}"
        state: directory

    - name: extract compressed apps into /product/[app_dir]
      ansible.builtin.unarchive:
        src: "files/{{ apps.postgresql.compressed }}"
        dest: "{{ apps.postgresql.app_base_dir }}"
        owner: "{{ servers[group_names[0]]['sys_users'][0].user.name }}"
        group: "{{ servers[group_names[0]]['sys_users'][0].user.groups }}"

    - name: create ver sym links
      ansible.builtin.file:
        dest: "{{ apps.postgresql.ver }}"
        src: "{{ apps.postgresql.version }}"
        owner: "{{ servers[group_names[0]]['sys_users'][0].user.name }}"
        group: "{{ servers[group_names[0]]['sys_users'][0].user.groups }}"
        state: link

