---
- hosts: DB
  become: yes
  gather_facts: false

  vars_files:
    - vars.yml

  roles:
    - role: firewall
      tags: firewall
    - role: groups
      tags: groups
    - role: users
      tags: users
    - role: etcd
      tags: etcd
    - role: pkgs
      tags: pkgs
    - role: pips
      tags: pips
    - role: postgresql
      tags: postgresql

