---
# tasks file for roles/etcd
- name: deploy etcd runtime
  block:
    - name: extract compressed apps into /product/[app_dir]
      ansible.builtin.unarchive:
        src: "http://{{ ansible_ip }}/download/{{ apps.etcd.compressed }}"
        dest: "/tmp/"
        remote_src: yes

    - name: create data dir
      ansible.builtin.file:
        path: "{{ etcd.data_dir }}"
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
        state: directory

    - name: create ssl dir
      ansible.builtin.file:
        path: "{{ etcd.ssl_dir }}"
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
        state: directory

    - name: Download CA cert
      ansible.builtin.get_url:
        url: "http://{{ ansible_ip }}/download/{{ certs.ca.src }}"
        dest: "{{ certs.ca.dest }}"
        mode: 0644
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
        force: true

    - name: Download key
      ansible.builtin.get_url:
        url: "http://{{ ansible_ip }}/download/{{ certs.key.src }}"
        dest: "{{ certs.key.dest }}"
        mode: 0600
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
        force: true

    - name: Download cert
      ansible.builtin.get_url:
        url: "http://{{ ansible_ip }}/download/{{ certs.crt.src }}"
        dest: "{{ certs.crt.dest }}"
        mode: 0644
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
        force: true

    - name: copy the etcd binaries in the remote machines
      ansible.builtin.copy:
        src: "/tmp/{{ apps.etcd.version }}/{{ item }}"
        dest: "/usr/bin/"
        mode: 0655
        remote_src: yes
      loop:
        - etcdutl
        - etcdctl
        - etcd

    - name: write etcd service jinja2 templates
      ansible.builtin.template:
        src: "{{ etcd.templates.service.src }}"
        dest: "{{ etcd.templates.service.dest }}"

    - name: write etcd env jinja2 templates
      ansible.builtin.template:
        src: "{{ etcd.templates.etcdenv.src }}"
        dest: "{{ etcd.templates.etcdenv.dest }}"
        owner: "{{ sys_users.etcd.name }}"
        group: "{{ sys_groups.etcd.name }}"
