---
# tasks file for firewall

- name: allowing firewalld ports on the public zone
  ansible.posix.firewalld:
    zone: public
    port: "{{item}}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ servers[group_names[0]]['ports'] }}"

- name: permit traffic in default zone for services
  ansible.posix.firewalld:
    zone: public
    service: "{{item}}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ servers[group_names[0]]['services'] }}"

- name: allowing env specific firewalld ports on the public zone
  ansible.posix.firewalld:
    zone: public
    port: "{{item}}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ ports }}"
  when: "ports is defined"

